In [63]:
import pandas as pd
import numpy as np

In [64]:
preprocessed_absenteeism=pd.read_csv('/Users/raghavverma/Downloads/Absenteeism_preprocessed.csv')

In [65]:
df=preprocessed_absenteeism.copy()

In [66]:
df.describe()

Reason_1    Reason_2    Reason_3    Reason_4  Month Value  \
count  700.000000  700.000000  700.000000  700.000000    700.00000   
mean     0.250000    0.008571    0.090000    0.597143      6.36000   
std      0.433322    0.092250    0.286386    0.490823      3.50501   
min      0.000000    0.000000    0.000000    0.000000      1.00000   
25%      0.000000    0.000000    0.000000    0.000000      3.00000   
50%      0.000000    0.000000    0.000000    1.000000      6.00000   
75%      0.250000    0.000000    0.000000    1.000000     10.00000   
max      1.000000    1.000000    1.000000    1.000000     12.00000   

       Day of the week  Transportation Expense  Distance to Work         Age  \
count       700.000000              700.000000        700.000000  700.000000   
mean          2.011429              222.347143         29.892857   36.417143   
std           1.480396               66.312960         14.804446    6.379083   
min           0.000000              118.000000          5.000000   27.000000   
25%           1.000000              179.000000         16.000000   31.000000   
50%           2.000000              225.000000         26.000000   37.000000   
75%           3.000000              260.000000         50.000000   40.000000   
max           6.000000              388.000000         52.000000   58.000000   

       Daily Work Load Average  Body Mass Index   Education    Children  \
count               700.000000       700.000000  700.000000  700.000000   
mean                271.801774        26.737143    0.167143    1.021429   
std                  40.021804         4.254701    0.373370    1.112215   
min                 205.917000        19.000000    0.000000    0.000000   
25%                 241.476000        24.000000    0.000000    0.000000   
50%                 264.249000        25.000000    0.000000    1.000000   
75%                 294.217000        31.000000    0.000000    2.000000   
max                 378.884000        38.000000    1.000000    4.000000   

             Pets  Absenteeism Time in Hours  
count  700.000000                 700.000000  
mean     0.687143                   6.761429  
std      1.166095                  12.670082  
min      0.000000                   0.000000  
25%      0.000000                   2.000000  
50%      0.000000                   3.000000  
75%      1.000000                   8.000000  
max      8.000000                 120.000000

In [67]:
df['Absenteeism Time in Hours'].median()

3.0

In [68]:
targets=np.where(df['Absenteeism Time in Hours']>df['Absenteeism Time in Hours'].median(),1,0)

In [69]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [70]:
df['Excessive absenteeism']=targets

In [71]:
data_with_targets=df.drop(['Absenteeism Time in Hours'],axis=1)

In [72]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [73]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [74]:
df_unscaled=data_with_targets[['Month Value','Day of the week','Transportation Expense','Distance to Work','Age','Daily Work Load Average','Body Mass Index','Children','Pets']]

In [75]:
df_unscaled

Month Value  Day of the week  Transportation Expense  Distance to Work  \
0              7                1                     289                36   
1              7                1                     118                13   
2              7                2                     179                51   
3              7                3                     279                 5   
4              7                3                     289                36   
..           ...              ...                     ...               ...   
695            5                2                     179                22   
696            5                2                     225                26   
697            5                3                     330                16   
698            5                3                     235                16   
699            5                3                     291                31   

     Age  Daily Work Load Average  Body Mass Index  Children  Pets  
0     33                  239.554               30         2     1  
1     50                  239.554               31         1     0  
2     38                  239.554               31         0     0  
3     39                  239.554               24         2     0  
4     33                  239.554               30         2     1  
..   ...                      ...              ...       ...   ...  
695   40                  237.656               22         2     0  
696   28                  237.656               24         1     2  
697   28                  237.656               25         0     0  
698   32                  237.656               25         0     0  
699   40                  237.656               25         1     1  

[700 rows x 9 columns]

In [76]:
from sklearn.preprocessing import StandardScaler
df_std=StandardScaler().fit_transform(df_unscaled)


In [77]:
df_std

array([[ 0.18272635, -0.68370352,  1.00584437, ...,  0.76743118,
         0.88046927,  0.26848661],
       [ 0.18272635, -0.68370352, -1.57468098, ...,  1.00263338,
        -0.01928035, -0.58968976],
       [ 0.18272635, -0.00772546, -0.6541427 , ...,  1.00263338,
        -0.91902997, -0.58968976],
       ...,
       [-0.3882935 ,  0.66825259,  1.62456682, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.66825259,  0.19094163, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.66825259,  1.03602595, ..., -0.40857982,
        -0.01928035,  0.26848661]])

In [78]:
df_std=pd.DataFrame(df_std,columns=['Month Value','Day of the week','Transportation Expense','Distance to Work','Age','Daily Work Load Average','Body Mass Index','Children','Pets'])

In [79]:
df_un=data_with_targets[['Reason_1','Reason_2','Reason_3','Reason_4','Education']]

In [80]:
df_un=pd.concat([df_un,df_std],axis=1)

In [81]:
df_un.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education',
       'Month Value', 'Day of the week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Children', 'Pets'], dtype=object)

In [82]:
new_columns=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month Value', 'Transportation Expense',
       'Age', 'Body Mass Index','Education',
       'Children', 'Pets']

In [83]:
df_un=df_un[new_columns]

In [84]:
df_un

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [85]:
unscaled_inputs=df_un

In [86]:
unscaled_inputs=np.array(unscaled_inputs)

In [87]:
unscaled_inputs

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.88046927,  0.26848661],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.91902997, -0.58968976],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.01928035,  0.26848661]])

# SCALING INPUTS

# Splitting Data


In [88]:
from sklearn.model_selection import train_test_split

In [89]:
train_test_split(unscaled_inputs,targets)

[array([[ 0.        ,  0.        ,  1.        , ...,  1.        ,
         -0.01928035,  0.26848661],
        [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         -0.91902997, -0.58968976],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         -0.01928035, -0.58968976],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  1.        ,
         -0.91902997, -0.58968976],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         -0.91902997, -0.58968976],
        [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         -0.91902997, -0.58968976]]),
 array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          2.67996851, -0.58968976],
        [ 0.        ,  0.        ,  1.        , ...,  0.        ,
          0.88046927, -0.58968976],
        [ 0.        ,  0.        ,  1.        , ...,  0.        ,
          0.88046927,  0.26848661],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  

In [90]:
x_train,x_test,y_train,y_test=train_test_split(unscaled_inputs,targets,train_size=0.80,random_state=20)

In [91]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [92]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


# LogisticRegression model fitting

In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
from sklearn import metrics

In [95]:
reg=LogisticRegression()

In [96]:
reg.fit(x_train,y_train)

LogisticRegression()

In [97]:
reg.score(x_train,y_train)

0.7732142857142857

# Manual accuracy

In [98]:
output_train=reg.predict(x_train)

In [99]:
np.sum((output_train==y_train))

433

In [100]:
output_train.shape[0]

560

In [101]:
np.sum((output_train==y_train))/output_train.shape[0]

0.7732142857142857

# Finding intercept and coefficient

In [102]:
reg.intercept_

array([-1.6474549])

In [103]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [104]:
features=data_with_targets.iloc[:,:-1]

In [105]:
feature_name=df_un.columns.values

In [106]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)

In [107]:
summary_table['Coefficients']=np.transpose(reg.coef_)

In [108]:
summary_table.index=summary_table.index+1

In [109]:
summary_table.loc[0]=['Intercept',reg.intercept_[0]]

In [110]:
summary_table=summary_table.sort_index()

In [111]:
summary_table

Feature name  Coefficients
0                Intercept     -1.647455
1                 Reason_1      2.800197
2                 Reason_2      0.951884
3                 Reason_3      3.115553
4                 Reason_4      0.839001
5              Month Value      0.158930
6   Transportation Expense      0.605284
7                      Age     -0.169891
8          Body Mass Index      0.279811
9                Education     -0.210533
10                Children      0.348262
11                    Pets     -0.277396

In [112]:
summary_table['Coefficients']=summary_table['Coefficients'].astype(float)

In [113]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficients)

In [114]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficients  Odds_ratio
3                 Reason_3      3.115553   22.545903
1                 Reason_1      2.800197   16.447892
2                 Reason_2      0.951884    2.590585
4                 Reason_4      0.839001    2.314054
6   Transportation Expense      0.605284    1.831773
10                Children      0.348262    1.416604
8          Body Mass Index      0.279811    1.322880
5              Month Value      0.158930    1.172256
7                      Age     -0.169891    0.843757
9                Education     -0.210533    0.810152
11                    Pets     -0.277396    0.757754
0                Intercept     -1.647455    0.192539

# testing data

In [115]:
reg.score(x_test,y_test)

0.75

In [116]:
predicted_proba=reg.predict_proba(x_test)

In [117]:
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [122]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

In [119]:
df_un.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1     0.182726   
1         0         0         0         0     0.182726   
2         0         0         0         1     0.182726   
3         1         0         0         0     0.182726   
4         0         0         0         1     0.182726   

   Transportation Expense       Age  Body Mass Index  Education  Children  \
0                1.005844 -0.536062         0.767431          0  0.880469   
1               -1.574681  2.130803         1.002633          0 -0.019280   
2               -0.654143  0.248310         1.002633          0 -0.919030   
3                0.854936  0.405184        -0.643782          0  0.880469   
4                1.005844 -0.536062         0.767431          0  0.880469   

       Pets  
0  0.268487  
1 -0.589690  
2 -0.589690  
3 -0.589690  
4  0.268487

In [124]:
reg.predict(df_un)


array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,

In [125]:
reg.score(df_un,targets)

0.7685714285714286

In [129]:
reg.predict_proba(df_un)[:,1]

array([0.59082405, 0.07612942, 0.25096368, 0.87219417, 0.59082405,
       0.25096368, 0.48334245, 0.60505988, 0.78621895, 0.30530219,
       0.91589146, 0.91589146, 0.91589146, 0.70427049, 0.25096368,
       0.70542319, 0.25096368, 0.76549995, 0.70015424, 0.44936139,
       0.87582448, 0.71363274, 0.8743431 , 0.61584977, 0.9363924 ,
       0.4946805 , 0.60174687, 0.16777191, 0.9363924 , 0.25958951,
       0.77354707, 0.67439906, 0.31501022, 0.67439906, 0.25958951,
       0.4946805 , 0.60174687, 0.82771772, 0.17531704, 0.61584977,
       0.21048403, 0.15049817, 0.26840558, 0.91879734, 0.29244941,
       0.15049817, 0.26840558, 0.41275772, 0.62652682, 0.83321968,
       0.42027236, 0.14449042, 0.28100474, 0.15049817, 0.40591571,
       0.08276298, 0.79200758, 0.26840558, 0.65147011, 0.46061297,
       0.26840558, 0.62652682, 0.27740888, 0.15639189, 0.08627349,
       0.14875272, 0.27740888, 0.29026298, 0.15639189, 0.29026298,
       0.47190484, 0.42379818, 0.27740888, 0.29026298, 0.94476

In [130]:
prob=reg.predict_proba(df_un)[:,1]

In [133]:
df_new=data_with_targets.iloc[:,:-1]

In [135]:
df_new["Probability"]=prob

In [137]:
pred=[]
for i in prob:
    if i<0.5:
        i=0
    else:
        i=1
    pred.append(i)
print(pred)

[1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 

In [138]:
df_new["Prediction"]=pred

In [145]:
pd.options.display.max_rows=1000

In [140]:
df_new.to_csv('/Users/raghavverma/Documents/Absenteeism_final.csv')